### ISSUE TITLE
Travis Check on pull request fails

### ISSUE THREAD

**Issue by fernandezc** [spectrochempy/spectrochempy#201]
For developer: Travis check on pull request is not working anymore (since a week or so). It seems it is a known bug, but all advices found on this subject did not work to solve this problem.  Thus to merge we must to disable the PR checking in `settings/branches'  and `set branch protection' rule to disable the check. 

![Capture d’écran 2021-02-02 à 11 53 50](https://user-images.githubusercontent.com/2428474/106590523-7aad5880-654d-11eb-9f00-9cef7ceb6407.png)

**Comment by fernandezc** [comment]
After modification of the travis.yaml  it's now working. 

```
- stage: pytest-linux-3.9
      if: branch NOT IN (master)
      env:
      - TEST=true
      - CONDAPY=3.9
```
becomes 
```
- stage: pytest-linux-3.9
      if: type == pull_request or branch NOT IN (master)
      env:
      - TEST=true
      - CONDAPY=3.9
```
The problem was that no job was created with the previous setting.
